name: build

on:
  workflow_dispatch:
    inputs:
      commitHash:
        description: 'webrtc-sdk commit hash'
        default: ''
        required: true
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    # branches-ignore:
    #   - daily
    tags:
      - '*'

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        name:
          - macos_arm64
          - ios
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 13.0
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
    - run: brew install ninja
    - run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: webrtc.${{ matrix.name }}.tar.gz
        path: build/_package/${{ matrix.name }}/webrtc.tar.gz
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        name:
          - android
    runs-on: ${{ matrix.name == 'ubuntu-22.04_x86_64' && 'ubuntu-22.04' || 'ubuntu-20.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Disk Cleanup
        run: |
          set -x
          df -h
          sudo du -h -d1 /usr/local
          sudo du -h -d1 /usr/local/share
          sudo du -h -d1 /usr/local/lib
          sudo du -h -d1 /usr/share
          docker rmi `docker images -q -a`
          # 4.6G
          sudo rm -rf /usr/local/.ghcup
          # 1.7G
          sudo rm -rf /usr/share/swift
          # 1.4G
          sudo rm -rf /usr/share/dotnet
          # 13G
          sudo rm -rf /usr/local/lib/android
          df -h
      - run: ./build.${{ matrix.name }}.sh "${{ github.event.inputs.commitHash }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webrtc.${{ matrix.name }}.tar.gz
          path: build/_package/${{ matrix.name }}/webrtc.tar.gz
  create-release:
    name: Create Release
    if: contains(github.ref, 'tags/m')
    needs:
      - build-macos
      - build-linux
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/actions/download
        with:
          platform: macos_arm64
      - uses: ./.github/actions/download
        with:
          platform: ios
      - uses: ./.github/actions/download
        with:
          platform: android
      - name: Env to output
        run: |
          echo "package_paths<<EOF" >> $GITHUB_OUTPUT
          cat package_paths.env >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: env
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:
            ${{ steps.env.outputs.package_paths }}